require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AwfulsController do

  # This should return the minimal set of attributes required to create a valid
  # Awful. As you add validations to Awful, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AwfulsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all awfuls as @awfuls" do
      awful = Awful.create! valid_attributes
      get :index, {}, valid_session
      assigns(:awfuls).should eq([awful])
    end
  end

  describe "GET show" do
    it "assigns the requested awful as @awful" do
      awful = Awful.create! valid_attributes
      get :show, {:id => awful.to_param}, valid_session
      assigns(:awful).should eq(awful)
    end
  end

  describe "GET new" do
    it "assigns a new awful as @awful" do
      get :new, {}, valid_session
      assigns(:awful).should be_a_new(Awful)
    end
  end

  describe "GET edit" do
    it "assigns the requested awful as @awful" do
      awful = Awful.create! valid_attributes
      get :edit, {:id => awful.to_param}, valid_session
      assigns(:awful).should eq(awful)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Awful" do
        expect {
          post :create, {:awful => valid_attributes}, valid_session
        }.to change(Awful, :count).by(1)
      end

      it "assigns a newly created awful as @awful" do
        post :create, {:awful => valid_attributes}, valid_session
        assigns(:awful).should be_a(Awful)
        assigns(:awful).should be_persisted
      end

      it "redirects to the created awful" do
        post :create, {:awful => valid_attributes}, valid_session
        response.should redirect_to(Awful.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved awful as @awful" do
        # Trigger the behavior that occurs when invalid params are submitted
        Awful.any_instance.stub(:save).and_return(false)
        post :create, {:awful => {  }}, valid_session
        assigns(:awful).should be_a_new(Awful)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Awful.any_instance.stub(:save).and_return(false)
        post :create, {:awful => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested awful" do
        awful = Awful.create! valid_attributes
        # Assuming there are no other awfuls in the database, this
        # specifies that the Awful created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Awful.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => awful.to_param, :awful => { "these" => "params" }}, valid_session
      end

      it "assigns the requested awful as @awful" do
        awful = Awful.create! valid_attributes
        put :update, {:id => awful.to_param, :awful => valid_attributes}, valid_session
        assigns(:awful).should eq(awful)
      end

      it "redirects to the awful" do
        awful = Awful.create! valid_attributes
        put :update, {:id => awful.to_param, :awful => valid_attributes}, valid_session
        response.should redirect_to(awful)
      end
    end

    describe "with invalid params" do
      it "assigns the awful as @awful" do
        awful = Awful.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Awful.any_instance.stub(:save).and_return(false)
        put :update, {:id => awful.to_param, :awful => {  }}, valid_session
        assigns(:awful).should eq(awful)
      end

      it "re-renders the 'edit' template" do
        awful = Awful.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Awful.any_instance.stub(:save).and_return(false)
        put :update, {:id => awful.to_param, :awful => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested awful" do
      awful = Awful.create! valid_attributes
      expect {
        delete :destroy, {:id => awful.to_param}, valid_session
      }.to change(Awful, :count).by(-1)
    end

    it "redirects to the awfuls list" do
      awful = Awful.create! valid_attributes
      delete :destroy, {:id => awful.to_param}, valid_session
      response.should redirect_to(awfuls_url)
    end
  end

end
